title: Eknoor Kaur Sandhu
url: "https://eknoor.xyz"
baseurl: ""
description: "Research, projects and community work across biology, mathematics, AI and economics."

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes

sass:
    style: compressed
    sass_dir: _sass

collections:
  projects:
    output: true
